
services:
  frontend:
    build: frontend/.
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_API_URL: http://backend:5000

  backend:
    build: backend/.
    ports:
      - 5000:5000
    environment:
      frontend_host: http://frontend:3000